### ISSUE TITLE
AOS CICD work checklist

### ISSUE THREAD

**Issue by ChoiDaeYoung-94** [ChoiDaeYoung-94/unity-cicd#12]
AOS CICD 관련 work checklist

### STEP 1

build에 필요한 src를 추가 후 cli 통해 aos build 추출

- [x] ChoiDaeYoung-94/unity-cicd#13
- [x] ChoiDaeYoung-94/unity-cicd#16
- [x] ChoiDaeYoung-94/unity-cicd#18
- [x] ChoiDaeYoung-94/unity-cicd#19
- [x] ChoiDaeYoung-94/unity-cicd#23

### STEP 2

STEP 1 에서 나온 CLI 고도화

- [x] ChoiDaeYoung-94/unity-cicd#27
- [x] ChoiDaeYoung-94/unity-cicd#28
- [x] ChoiDaeYoung-94/unity-cicd#29
- [x] ChoiDaeYoung-94/unity-cicd#30
- [x] ChoiDaeYoung-94/unity-cicd#36

### STEP 3

STEP 1, 2 에서 나온 CLI를 Github Action에 녹인 후 특정 상황에 맞게 build 추출

- [x] ChoiDaeYoung-94/unity-cicd#38
- [x] ChoiDaeYoung-94/unity-cicd#39
- [x] ChoiDaeYoung-94/Incremental#17
- [x] ChoiDaeYoung-94/Incremental#19
- [x] ChoiDaeYoung-94/unity-cicd#45
- [x] ChoiDaeYoung-94/unity-cicd#46
- [x] ChoiDaeYoung-94/unity-cicd#41

### STEP 4

STEP 3 에서 작업한 yml에 CD 내용 추가

- [x] ChoiDaeYoung-94/unity-cicd#47
- [x] ChoiDaeYoung-94/Incremental#21
- [x] #53
- [x] #55
- [x] ChoiDaeYoung-94/unity-cicd#49

**Comment by ChoiDaeYoung-94** [comment]
AOS CICD work checklist를 모두 마쳤으므로 본 이슈 닫음
